import { CourseTimetable } from '../schemas';

export const iti_1121_fall_2020_transformed = {
  id: '7035',
  term: { season: 'fall', year: 2020 },
  subject_code: 'ITI',
  course_code: '1120',
  course_name: 'Introduction to Computing I',
  school: 'uottawa',
  sections: {
    A: {
      id: 'A',
      timetable_id: '7035',
      label: 'A',
      instructor: 'Vida Dujmovic',
      description: '',
      components: {
        'A01-LAB': {
          id: 'A01-LAB',
          section_id: 'A',
          timetable_id: '7035',
          day: 'WE',
          room: '',
          type: 'LAB',
          label: 'A01-LAB',
          status: 'OPEN',
          end_date: '2020-12-09',
          end_time: '18:50',
          instructor: 'Vida Dujmovic',
          start_date: '2020-09-09',
          start_time: '16:00',
          description: '',
          session_type: 'FULLSESS',
        },
        'A02-LAB': {
          id: 'A02-LAB',
          section_id: 'A',
          timetable_id: '7035',
          day: 'TH',
          room: '',
          type: 'LAB',
          label: 'A02-LAB',
          status: 'OPEN',
          end_date: '2020-12-09',
          end_time: '11:20',
          instructor: 'Vida Dujmovic',
          start_date: '2020-09-09',
          start_time: '08:30',
          description: '',
          session_type: 'FULLSESS',
        },
        'A03-LAB': {
          id: 'A03-LAB',
          section_id: 'A',
          timetable_id: '7035',
          day: 'TH',
          room: '',
          type: 'LAB',
          label: 'A03-LAB',
          status: 'OPEN',
          end_date: '2020-12-09',
          end_time: '18:50',
          instructor: 'Vida Dujmovic',
          start_date: '2020-09-09',
          start_time: '16:00',
          description: '',
          session_type: 'FULLSESS',
        },
        'A04-LAB': {
          id: 'A04-LAB',
          section_id: 'A',
          timetable_id: '7035',
          day: 'FR',
          room: '',
          type: 'LAB',
          label: 'A04-LAB',
          status: 'OPEN',
          end_date: '2020-12-09',
          end_time: '17:20',
          instructor: 'Vida Dujmovic',
          start_date: '2020-09-09',
          start_time: '14:30',
          description: '',
          session_type: 'FULLSESS',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          section_id: 'A',
          timetable_id: '7035',
          day: 'MO',
          room: '',
          type: 'LEC',
          label: 'A00-LEC',
          status: 'OPEN',
          end_date: '2020-12-09',
          end_time: '14:20',
          instructor: 'Vida Dujmovic',
          start_date: '2020-09-09',
          start_time: '13:00',
          description: '',
          session_type: 'FULLSESS',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          section_id: 'A',
          timetable_id: '7035',
          day: 'WE',
          room: '',
          type: 'LEC',
          label: 'A00-LEC',
          status: 'OPEN',
          end_date: '2020-12-09',
          end_time: '12:50',
          instructor: 'Vida Dujmovic',
          start_date: '2020-09-09',
          start_time: '11:30',
          description: '',
          session_type: 'FULLSESS',
        },
      },
    },
  },
} satisfies CourseTimetable;
