import { DbTimetableRow } from '../types';

export const iti_1121_fall_2020_source = {
  id: '7035',
  year: 2020,
  season: 'fall',
  subject_code: 'ITI',
  course_code: '1120',
  course_name: 'Introduction to Computing I',
  school: 'uottawa',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      components: {
        LAB: {
          A01: [
            {
              id: 'A01-LAB-0',
              day: 'WE',
              room: '',
              type: 'LAB',
              label: 'A01-LAB',
              status: 'OPEN',
              end_date: '2020-10-09',
              end_time: '18:50',
              instructor: 'Vida Dujmovic',
              start_date: '2020-09-09',
              start_time: '16:00',
              description: '',
              session_type: 'FULLSESS',
            },
            {
              id: 'A01-LAB-1',
              day: 'WE',
              room: '',
              type: 'LAB',
              label: 'A01-LAB',
              status: 'OPEN',
              end_date: '2020-12-09',
              end_time: '18:50',
              instructor: 'Vida Dujmovic',
              start_date: '2020-10-09',
              start_time: '16:00',
              description: '',
              session_type: 'FULLSESS',
            },
          ],
          A02: [
            {
              id: 'A02-LAB-0',
              day: 'TH',
              room: '',
              type: 'LAB',
              label: 'A02-LAB',
              status: 'OPEN',
              end_date: '2020-12-09',
              end_time: '11:20',
              instructor: 'Vida Dujmovic',
              start_date: '2020-09-09',
              start_time: '08:30',
              description: '',
              session_type: 'FULLSESS',
            },
          ],
          A03: [
            {
              id: 'A03-LAB-0',
              day: 'TH',
              room: '',
              type: 'LAB',
              label: 'A03-LAB',
              status: 'OPEN',
              end_date: '2020-12-09',
              end_time: '18:50',
              instructor: 'Vida Dujmovic',
              start_date: '2020-09-09',
              start_time: '16:00',
              description: '',
              session_type: 'FULLSESS',
            },
          ],
          A04: [
            {
              id: 'A04-LAB-0',
              day: 'FR',
              room: '',
              type: 'LAB',
              label: 'A04-LAB',
              status: 'OPEN',
              end_date: '2020-12-09',
              end_time: '17:20',
              instructor: 'Vida Dujmovic',
              start_date: '2020-09-09',
              start_time: '14:30',
              description: '',
              session_type: 'FULLSESS',
            },
          ],
        },
        LEC: {
          A00: [
            {
              id: 'A00-LEC-0',
              day: 'MO',
              room: '',
              type: 'LEC',
              label: 'A00-LEC',
              status: 'OPEN',
              end_date: '2020-12-09',
              end_time: '14:20',
              instructor: 'Vida Dujmovic',
              start_date: '2020-09-09',
              start_time: '13:00',
              description: '',
              session_type: 'FULLSESS',
            },
            {
              id: 'A00-LEC-1',
              day: 'WE',
              room: '',
              type: 'LEC',
              label: 'A00-LEC',
              status: 'OPEN',
              end_date: '2020-12-09',
              end_time: '12:50',
              instructor: 'Vida Dujmovic',
              start_date: '2020-09-09',
              start_time: '11:30',
              description: '',
              session_type: 'FULLSESS',
            },
          ],
        },
      },
      instructor: 'Vida Dujmovic',
      description: '',
    },
  },
} satisfies DbTimetableRow;
