import { ScheduleEntry } from '@modules/schedule_file_formatter';

export const iti_1121_fall_2020_entries = [
  {
    course_code: '1120',
    course_name: 'Introduction to Computing I',
    day_of_week: 'WE',
    description: '',
    end_date: '2020-12-09',
    end_time: '18:50',
    id: 'A01-LAB-0',
    instructor: 'Vida Dujmovic',
    label: 'A01-LAB',
    room: '',
    school: 'uottawa',
    section_id: 'A',
    section_label: 'A',
    session_type: 'FULLSESS',
    start_date: '2020-09-09',
    start_time: '16:00',
    status: 'OPEN',
    subject_code: 'ITI',
    term: { season: 'fall', year: 2020 },
    type: 'LAB',
  },
  {
    course_code: '1120',
    course_name: 'Introduction to Computing I',
    day_of_week: 'MO',
    description: '',
    end_date: '2020-12-09',
    end_time: '14:20',
    id: 'A00-LEC-0',
    instructor: 'Vida Dujmovic',
    label: 'A00-LEC',
    room: '',
    school: 'uottawa',
    section_id: 'A',
    section_label: 'A',
    session_type: 'FULLSESS',
    start_date: '2020-09-09',
    start_time: '13:00',
    status: 'OPEN',
    subject_code: 'ITI',
    term: { season: 'fall', year: 2020 },
    type: 'LEC',
  },
  {
    course_code: '1120',
    course_name: 'Introduction to Computing I',
    day_of_week: 'WE',
    description: '',
    end_date: '2020-12-09',
    end_time: '12:50',
    id: 'A00-LEC-1',
    instructor: 'Vida Dujmovic',
    label: 'A00-LEC',
    room: '',
    school: 'uottawa',
    section_id: 'A',
    section_label: 'A',
    session_type: 'FULLSESS',
    start_date: '2020-09-09',
    start_time: '11:30',
    status: 'OPEN',
    subject_code: 'ITI',
    term: { season: 'fall', year: 2020 },
    type: 'LEC',
  },
] satisfies ScheduleEntry[];
