##############################################################################
#       IMPORTS
##############################################################################

# Standard Library
## Logging
import logging
logging.getLogger(__name__)
##
import argparse
import json
import re

# Third-party
import requests

# First-party
from . import _config
from . import _utils
import uoapi
import notifier.logda as logda

# Typing
from typing import (
    AnyStr,
    Callable,
    Dict,
    Generator,
    Iterable,
    List,
    Optional,
    Sequence,
    Set,
    Tuple,
    TypeVar,
)
S = TypeVar("S")
T = TypeVar("T")
U = TypeVar("U")


##############################################################################
#       CONFIG
##############################################################################


class TimetableConfig:
    timestamp: _config.EndpointConfig
    timetables: _config.EndpointConfig
    users: _config.EndpointConfig

    def __init__(self,
        timestamp: _config.EndpointConfig,
        timetables: _config.EndpointConfig,
        users: _config.EndpointConfig,
    ):
        self.timestamp = timestamp
        self.timetables = timetables
        self.users = users

    @classmethod
    def from_args(cls, args):
        return cls(
            _config.make_timestamp_config(args),
            _config.make_timetable_config(args),
            _config.make_users_config(args),
        )

    @classmethod
    def default(cls):
        return cls.from_args(
            _config.EndpointConfig.configure_parser().parse_args([])
        )

    @staticmethod
    def configure_parser(parser):
        return _config.EndpointConfig.configure_parser(parser)


# Communicating with the notifier
DEFAULT_TT_CONFIG = TimetableConfig.default()

##############################################################################
#       UPDATE TIMETABLES
##############################################################################


class TimetableUpdater:
    """This class handles updating the timetables in the DA.
    
    Initializing an instance of this class merely sets
    global parameters and state; in order to actually
    update the DA, the `TimetableUpdater.update_timetables`
    method needs to be called.
    
    The data which is fed to the DA is generated by
    the `uoapi` scraper.
    """
    def __init__(self,
        retries: int = 2,
        notes: Optional["TimetableNotifier"] = None,
        saveraw: Optional[AnyStr] = None,
        config: TimetableConfig = DEFAULT_TT_CONFIG,
    ):
        """
        Throughout the life of this object, `self.notes` is used
        to store messages which should be sent to the maintainers
        of this project (as determined by the `notifier`).

        Args:
            retries:
            notes: A `TimetableNotifier` object; if `None`,
                a new `TimetableNotifier` object is instantiated.
            saveraw: A path to the folder in which the scraper
                should save the raw html from the scrape;
                if `None`, the raw html is not saved.
            config: A `TimetableConfig` object, providing access to all the
                endpoints that will need to be accessed by this updater.
        """
        if not isinstance(retries, int) or retries <= 0:
            retries = float("inf")
        self.retries = retries
        if notes is None:
            notes = TimetableNotifier()
        self.notes = notes
        self.saveraw = saveraw
        self.config = config

    #@TODO Once a subjects table is made in the DA,
    # get subjects from there,
    # and update subjects elsewhere.
    def scrape_subjects(self) -> Generator[List[Dict[str, str]], None, None]:
        """Scrape a list of all subjects.

        Yields:
            A `list` of subjects scraped by `uoapi`.
        """
        for output in self.notes.iter_wrap(
            uoapi.course.py_cli(),
            "Getting subjects: ",
            "CRITICAL",
        ):
            if "subjects" in output:
                yield output["subjects"]

    def get_subject_codes(self,
        subjects: List[Dict[str, str]]
    ) -> Set[str]:
        """Extract subject codes from subject information.

        Given a sequence of subjects
            as output by the scraper,
            returns set of subject codes.

        Args:
            subjects: A `list` of subjects as output by the scraper.

        Returns:
            A `set` of all the subject codes from `subjects`.
        """
        try:
            return {x["subject_code"]
                for x in subjects
                if "subject_code" in x
            }
        except Exception as e:
            logging.debug("Failed to get subject codes", exc_info=True)
            return set()

    def get_subjects(self) -> List[str]:
        """Get all valid subject codes.

        Returns:
            The sorted `list` of all subject codes.
        """
        for output in self.scrape_subjects():
            subjects = self.get_subject_codes(output)
            if len(subjects) > 0:
                logging.info("Got subjects: {}".format(", ".join(subjects)))
                return sorted(subjects)
            logging.warning("No subjects found")
        logging.error("Failed to get subjects")
        self.notes.maintainer("Could not get subjects from scraper")
        return None

    def searches_to_retry(self, messages: List[Dict[str, str]]) -> List[str]:
        """Examines the scraper messages to determine which
        searches should be retried.

        Returns:
            A `list` of the search terms which need to be retried.
        """
        retry = set()
        for msg in messages:
            msg = msg["message"]
            match = re.search("([A-Z]{3,4})_([1-5])(?![0-9])", msg)
            # Split searches which exceeded
            # the maximum number of results
            if ("exceeded maximum" in msg.lower()
                and match is not None
            ):
                s, n = match.groups()
                num = "300" if n != "5" else "500"
                num = s + "{}" + n + num
                searches = {num.format("<"), num.format(">")}
                logging.warning("Added searches: " + " ".join(searches))
                retry |= searches
        return list(retry)

    def handle_scraper_messages(self, messages: Iterable[Dict[str, str]]):
        """Notify maintainers of scraper errors.
        """
        for msg in messages:
            if msg["type"] == "error":
                self.notes.maintainer("[SCRAPER ERROR] "
                    + msg["message"]
                )

    def scrape_timetables(self,
        year: int,
        term: str,
        search_list: Optional[Sequence] = None,
    ) -> Generator[dict, None, None]:
        """Generates scraped course timetables.

        Calls the scraper on the `year` and `term` specified
        to find timetables for the courses/subjects in `search_list`.
        If `search_list` is empty or `None`, scrape all subjects.

        Note that the `self.retries` parameter is used here
        to determine how many times failing search terms should be
        retried.

        Args:
            year: The year to which the timetables should belong.
            term: The term to which timetables should belong.
            search_list: Courses and/or subjects to search for.
                For a complete list of terms which may be searched,
                consult the `uoapi` documentation.

        Yields:
            The timetable of each course which was found in the scrape.
        """
        #@TODO Factor; see line 336 (`update_timetables`)
        # See [CS-59]
        if search_list is None or len(search_list) == 0:
            search_list = self.get_subjects()
        tries_left = self.retries
        searched = set()
        while len(search_list) > 0 and tries_left > 0:
            searched |= set(search_list)
            retry = []
            for output in self.notes.iter_wrap(
                uoapi.timetable.py_cli(search_list, year, term, self.saveraw),
                "Getting timetables: ",
                "ERROR",
            ):
                for course in output.get("timetables", []):
                    yield course
                if len(output.get("messages", [])) > 0:
                    retry += self.searches_to_retry(output["messages"])
                    self.handle_scraper_messages(output["messages"])
            search_list = retry
            tries_left -= 1
        self.notes.maintainer("Scraped {} {} for: {}".format(
            term.capitalize(), year, ", ".join(sorted(searched))
        ))
        if len(search_list) > 0:
            leftover = "Leftover searches: " + " ".join(search_list)
            self.notes.maintainer(leftover)
            logging.warning(leftover)

    def send_timetable_to_da(self,
        course: dict,
        year: int,
        term: str,
    ) -> requests.models.Response:
        """
        Normzalizes the format of `course`,
        and sends it to the DA.

        Args:
            course: A course timetable.
            year: The year in which the timetable belongs.
            term: The term in which the timetable belongs.

        Returns:
            The response from the DA.
        """
        course = normalize_course(course, year, term)
        try:
            response = requests.put(
                self.config.timetables.endpoint,
                headers=self.config.timetables.headers,
                data=json.dumps(course),
            )
            if not(200 <= response.status_code < 300):
                raise Exception("Failed to send update to DA: {}".format(
                    response.status_code
                ))
        except Exception as e:
            message = "Could not update course: {} {}, {}{}".format(
                term.capitalize(), year,
                course["subject_code"], course["course_code"],
            )
            self.notes.maintainer(message)
            logging.warning(message)
            logging.debug(message, exc_info=True)
        else:
            message = "Updated course: {} {}, {}{}".format(
                term.capitalize(), year,
                course["subject_code"], course["course_code"],
            )
            logging.info(message)
            return response
        return None

    def update_timestamp(self,
        year: int,
        term: str,
        search_list: Optional[Sequence] = None,
    ):
        """Update the DA with the newest timestamp.
        """
        reason = ":".join(str(x).strip() for x in (year, term, "uottawa"))
        try:
            response = requests.put(
                self.config.timestamp.endpoint,
                headers=self.config.timetamp.headers,
                data=json.dumps({"reason": "{}-fullscrape".format(reason)})
            )
            if not(200 <= response.status_code < 300):
                raise Exception("Failed to update timestamp: {}".format(
                    response.status_code
                ))
        except Exception as e:
            message = "Could not update timestamp: {}-fullscrape".format(reason)
            self.notes.maintainer(message)
            logging.warning(message)
            logging.debug(message, exc_info=True)
        else:
            message = "Updated timestamp: {}".format(reason)
            logging.info(message)


    def update_timetables(self,
        year: int,
        term: str,
        search_list: Optional[Sequence] = None,
    ):
        """Update the DA with the newest timetable data.

        Calls the scraper to get the newest timetable data
        for the courses/subjects in `search_list`, 
        and sends the data to the DA.

        See `TimetableUpdater.scrape_timetables` for more information.

        Args:
            year: The year in which to cache timetables in the DA.
            term: The term in which to cache timetables in the DA.
            search_list: The courses/subjects/etc whose timetables
                are to be cached in the DA.  If `None`, cache all courses.

        """
        #@TODO Factor; see line 218 (`scrape_timetables`)
        # See [CS-59]
        is_full_scrape = search_list is None or len(search_list) == 0
        if is_full_scrape:
            self.notes.fullscrape = True
            logging.info("This is a FULLSCRAPE")
            self.update_timestamp(year, term, search_list)
        for course in self.scrape_timetables(year, term, search_list):
            response = self.send_timetable_to_da(course, year, term)
            #@TODO compute diff between course and response
            # if response is not None:
            #   ...
        self.notes.maintainer("Update complete.")
        self.notes.notify_maintainers(only_on_problems=not is_full_scrape)


##############################################################################
#       NORMALIZING COURSE TIMETABLES
##############################################################################


def normalize_course(
    course: dict,
    year: int,
    term: str
) -> dict:
    """Converts the timetable format of the scraper to that stored in the DA.

    Args:
        course: The course timetable as returned by the scraper.
        year: The year to which the timetable belongs.
        term: The term to which the timetable belongs.
    """
    output = {
        "sections": {},
        "school": 'uottawa',
        "term": term,
        "year": year,
        "course_code": course["course_code"],
        "subject_code": course["subject_code"],
        "course_name": course["course_name"],
    }
    year_terms = set()
    output["sections"] = dict(
        normalize_section(x, year_terms)
        for x in course["sections"]
    )
    if len(year_terms) != 1:
        logging.warning("Number of (year, term) pairs in sections of"
            + "{} {}, {}{} is {} != 1".format(
                term, year, output["subject_code"],
                output["course_code"], len(year_terms),
        ))
    elif year_terms != {(year, term)}:
        logging.warning("Year and from sections of {} {}, {}{}"
            + "do not match sections: {} {}".format(
                term, year, output["subject_code"],
                output["course_code"], *list(year_terms)[::-1]
        ))
    return output

def groupby(
    seq: Iterable[S],
    func: Callable[[S], T],
    postprocess: Callable[[S], U] = (lambda x:x)
) -> Dict[T, List[U]]:
    """Produce the equivalence classes of `seq` under `func`.

    If `postprocess` is given,
    it is applied to elements as they are added
    to their respective equivalence classes.

    Args:
        seq: Items to be grouped.
        func: The function indicating which items from `seq`
            are to be grouped together.
        postprocess: Function to be applied to the elements
            of `seq` when before they are placed in their groups.

    Returns:
        A `dict` mapping an image of elements of `seq` under `func`
            to a `list` of the elements of `seq` which map to that image.
            If `postprocess` is provided, the it is applied to
            the elements of `seq` before they are placed in the `list`.
    """
    equiv_classes = dict()
    for elt in seq:
        image = func(elt)
        if image not in equiv_classes:
            equiv_classes[image] = []
        equiv_classes[image].append(postprocess(elt))
    return equiv_classes

def normalize_section(
    section: dict,
    year_terms: Tuple[int, str],
) -> Tuple[str, dict]:
    """Normalizes the section data format.

    This function also pulls descriptions and instructors from
    the component-level to the section-level.

    Args:
        section: The `dict` containing the section information
            from the scraper.
        year_terms: Set to propogate up (year, term) tuples
            from the sections.

    Returns:
        A tuple of the section ID, and the reformated section.
    """
    sid = section["label"]
    year_terms.add((section["year"], section["term"]))
    components = section["components"]
    # Normalizing components
    type_count = dict()
    staff = set()
    profs = set()
    descs = set()
    components = [
        normalize_component(x, type_count, staff, profs, descs)
        for x in sorted(components, key=lambda comp:[
            comp[y] for y in ["label", "start_date", "day", "start_time"]
        ])
    ]
    components = {
        k: groupby(v, lambda x:x[0], lambda x:x[1])
        for k, v in groupby(components, lambda x:x[0], lambda x:x[1:]).items()
    }
    # Computing section properties derived from components
    # and returning with id
    profs = ", ".join(profs - {""})
    for ctype, cid, count in staff:
        components[ctype][cid][count]["instructor"] = profs
    return sid, {
        "id": sid,
        "label": sid,
        "instructor": profs,
        "description": ", ".join(descs - {""}),
        "components": components,
    }

def normalize_component(
    component: dict,
    type_count: Dict[Tuple[str, str], int],
    staff: Set[Tuple[str, str, int]],
    profs: Set[str],
    descs: Set[str],
) -> Tuple[str, str, dict]:
    """Normalizes the component data format.

    This function counts each type of component
    and propogates it up to the section-level for grouping.

    It also propogates the descriptions and instructors to
    the section-level.

    Args:
        components: The  `dict` containing the component
            information from the scraper.
        type_count: The `dict` mapping (component-type, component-id)
            tuples to the number of time-slots belonging to
            that component.
        staff: A `set` of the component time-slots (of lectures)
            which are missing instructors.
        profs: A `set` of the instructors (of lectures) of this section.
        descs: A `set` of the descriptions of components in this section.

    Returns:
        A tuple of the component type, ID, and the reformatter component.
    """
    # Transforming the data in each component to desired
    component = {k:v for k, v in component.items() if k != "section_id"}
    if "session_type" in component:
        component["session_type"] = component["session_type"].strip().strip(".").strip()
    prof = component.get("instructor", "").strip()
    component["instructor"] = "" if prof.lower() == "staff" else prof
    # Generating unique id (within a section)
    cid = component["label"]
    if "-" in cid:
        cid = cid.split("-")[0]
    ctype = component["type"]
    count = type_count.get((ctype, cid), 0)
    type_count[(ctype, cid)] = count + 1
    component["id"] = "-".join((cid, ctype, str(count)))
    # Collecting data for future use
    if ctype == "LEC":
        # Prof already normalized
        prof = component["instructor"]
        if prof == "":
            staff.add((ctype, cid, count))
        else:
            profs.add(prof)
    descs.add(component["description"].strip())
    # Returning type, id, and component
    return ctype, cid, component


##############################################################################
#       EXCEPTION AND NOTIFICATION HANDLING
##############################################################################


class TimetableNotifier(_utils.NotifierHandler):

    def __init__(self):
        super().__init__()
        self.fullscrape = False

    def format_data(self) -> dict:
        return {
            "messages": list(self.maintenance_msgs)
                +["---- ISSUES ----"]
                +["{message} -> {exception}".format(**x) for x in self.problems],
            "is_fullscrape": self.fullscrape,
            "subject": "Updating Timetables"
                + "[fullscrape]" if self.fullscrape else "",
            "priority": 1,
        }

    def clear_maintenance_msgs(self):
        """Clear the maintenance messages.

        Automatically called when maintainer notifications are sent.
        """
        super().clear_maintenance_msgs()
        self.fullscrape = False


##############################################################################
#       CLI AND MAIN
##############################################################################


def get_parser(**kwargs) -> argparse.ArgumentParser:
    """Create the argument parser used when this script is called.
    """
    parser = argparse.ArgumentParser(
        description="Update timetables.",
        **kwargs,
    )
    parser.add_argument("-y", "--year",
        action="store",
        metavar="YEAR",
        type=int,
        required=True,
        help="specify which year to query",
    )
    parser.add_argument("-t", "--term",
        action="store",
        metavar="TERM",
        choices=["winter", "summer", "fall"],
        required=True,
        help="specify which term to query (winter, summer, fall)",
    )
    parser.add_argument("-s", "--saveraw",
        action="store",
        metavar="/PATH/TO/DIR/",
        default=None,
        required=False,
        help="if given, save raw html in this folder",
    )
    parser.add_argument("subjects",
        action="store",
        nargs="*",
        help="subjects to update",
    )
    parser = logda.configure_parser(parser)
    parser = TimetableConfig.configure_parser(parser)
    return parser

def main(args=None, kwargs={}):
    """The main body of this script when called.

    Args:
        args: Script arguments to be parsed.  If `None`, then
            the command line arguments are parsed.
        kwargs: Arguments passed to `get_parser` which generates
            the `argparse.ArgumentParser`.
    """
    args = get_parser(**kwargs).parse_args(args)
    logda.configure_logging(args)
    TimetableUpdater(
        saveraw=args.saveraw,
        config=TimetableConfig.from_args(args),
    ).update_timetables(
        year=args.year,
        term=args.term,
        search_list=args.subjects,
    )


##############################################################################


if __name__ == '__main__':
    exit(main())
