import { Course } from '@models/Course';
import { CourseSection } from '@models/CourseSection';
import { CourseSectionComponent } from '@models/CourseSectionComponent';
import { courseResponseSchema } from '@services/Scheduler/schemas';

const csi2120_winter_raw = {
  data: {
    id: 753,
    school: 'uottawa',
    year: 2021,
    term: 'winter',
    subject_code: 'CSI',
    course_code: '2120',
    course_name: 'Programming Paradigms',
    sections: {
      A: {
        course_id: '753',
        id: 'A',
        label: 'A',
        instructor: 'Safaa Bedawi',
        description: '',
        num_components: 9,
        components: {
          'A01-LAB': {
            course_id: '753',
            section_id: 'A',
            id: 'A01-LAB',
            guid: '2021winter753AA01-LAB',
            label: 'A01-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'MO',
            start_timestamp: 30600,
            start_time: '08:30',
            start_time_12hr: '8:30 am',
            end_timestamp: 35400,
            end_time: '09:50',
            end_time_12hr: '9:50 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A02-LAB': {
            course_id: '753',
            section_id: 'A',
            id: 'A02-LAB',
            guid: '2021winter753AA02-LAB',
            label: 'A02-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'MO',
            start_timestamp: 30600,
            start_time: '08:30',
            start_time_12hr: '8:30 am',
            end_timestamp: 35400,
            end_time: '09:50',
            end_time_12hr: '9:50 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A03-LAB': {
            course_id: '753',
            section_id: 'A',
            id: 'A03-LAB',
            guid: '2021winter753AA03-LAB',
            label: 'A03-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'MO',
            start_timestamp: 30600,
            start_time: '08:30',
            start_time_12hr: '8:30 am',
            end_timestamp: 35400,
            end_time: '09:50',
            end_time_12hr: '9:50 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A04-LAB': {
            course_id: '753',
            section_id: 'A',
            id: 'A04-LAB',
            guid: '2021winter753AA04-LAB',
            label: 'A04-LAB',
            status: 'CLOSED',
            type: 'LAB',
            day: 'TH',
            start_timestamp: 36000,
            start_time: '10:00',
            start_time_12hr: '10:00 am',
            end_timestamp: 40800,
            end_time: '11:20',
            end_time_12hr: '11:20 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A05-LAB': {
            course_id: '753',
            section_id: 'A',
            id: 'A05-LAB',
            guid: '2021winter753AA05-LAB',
            label: 'A05-LAB',
            status: 'CLOSED',
            type: 'LAB',
            day: 'TH',
            start_timestamp: 36000,
            start_time: '10:00',
            start_time_12hr: '10:00 am',
            end_timestamp: 40800,
            end_time: '11:20',
            end_time_12hr: '11:20 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A07-LAB': {
            course_id: '753',
            section_id: 'A',
            id: 'A07-LAB',
            guid: '2021winter753AA07-LAB',
            label: 'A07-LAB',
            status: 'CLOSED',
            type: 'LAB',
            day: 'TH',
            start_timestamp: 41400,
            start_time: '11:30',
            start_time_12hr: '11:30 am',
            end_timestamp: 46200,
            end_time: '12:50',
            end_time_12hr: '12:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A00-LEC-0': {
            course_id: '753',
            section_id: 'A',
            id: 'A00-LEC-0',
            guid: '2021winter753AA00-LEC-0',
            label: 'A00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'TH',
            start_timestamp: 52200,
            start_time: '14:30',
            start_time_12hr: '2:30 pm',
            end_timestamp: 57000,
            end_time: '15:50',
            end_time_12hr: '3:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A00-LEC-1': {
            course_id: '753',
            section_id: 'A',
            id: 'A00-LEC-1',
            guid: '2021winter753AA00-LEC-1',
            label: 'A00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'TU',
            start_timestamp: 57600,
            start_time: '16:00',
            start_time_12hr: '4:00 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
          'A06-TUT': {
            course_id: '753',
            section_id: 'A',
            id: 'A06-TUT',
            guid: '2021winter753AA06-TUT',
            label: 'A06-TUT',
            status: 'OPEN',
            type: 'TUT',
            day: 'TH',
            start_timestamp: 57600,
            start_time: '16:00',
            start_time_12hr: '4:00 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Safaa Bedawi',
            session_type: 'FULLSESS',
            description: '',
          },
        },
      },
    },
  },
} as const;

export const iti_1120_winter_raw = {
  data: {
    id: 1562,
    school: 'uottawa',
    year: 2021,
    term: 'winter',
    subject_code: 'ITI',
    course_code: '1120',
    course_name: 'Introduction to Computing I',
    sections: {
      E: {
        course_id: '1562',
        id: 'E',
        label: 'Section E',
        instructor: 'Mohamad Hoda',
        description: 'This is the description',
        num_components: 7,
        components: {
          'E01-LAB': {
            course_id: '1562',
            section_id: 'E',
            id: 'E01-LAB',
            guid: '2021winter1562EE01-LAB',
            label: 'E01-LAB',
            status: 'CLOSED',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 52200,
            start_time: '14:30',
            start_time_12hr: '2:30 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: '',
          },
          'E02-LAB': {
            course_id: '1562',
            section_id: 'E',
            id: 'E02-LAB',
            guid: '2021winter1562EE02-LAB',
            label: 'E02-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'WE',
            start_timestamp: 52200,
            start_time: '14:30',
            start_time_12hr: '2:30 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: '',
          },
          'E03-LAB': {
            course_id: '1562',
            section_id: 'E',
            id: 'E03-LAB',
            guid: '2021winter1562EE03-LAB',
            label: 'E03-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 30600,
            start_time: '08:30',
            start_time_12hr: '8:30 am',
            end_timestamp: 40800,
            end_time: '11:20',
            end_time_12hr: '11:20 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: '',
          },
          'E04-LAB': {
            course_id: '1562',
            section_id: 'E',
            id: 'E04-LAB',
            guid: '2021winter1562EE04-LAB',
            label: 'E04-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'FR',
            start_timestamp: 63000,
            start_time: '17:30',
            start_time_12hr: '5:30 pm',
            end_timestamp: 73200,
            end_time: '20:20',
            end_time_12hr: '8:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: '',
          },
          'E05-LAB': {
            course_id: '1562',
            section_id: 'E',
            id: 'E05-LAB',
            guid: '2021winter1562EE05-LAB',
            label: 'E05-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 52200,
            start_time: '14:30',
            start_time_12hr: '2:30 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: '',
          },
          'E00-LEC-0': {
            course_id: '1562',
            section_id: 'E',
            id: 'E00-LEC-0',
            guid: '2021winter1562EE00-LEC-0',
            label: 'E00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'MO',
            start_timestamp: 46800,
            start_time: '13:00',
            start_time_12hr: '1:00 pm',
            end_timestamp: 51600,
            end_time: '14:20',
            end_time_12hr: '2:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: 'Online',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: 'Component Description',
          },
          'E00-LEC-1': {
            course_id: '1562',
            section_id: 'E',
            id: 'E00-LEC-1',
            guid: '2021winter1562EE00-LEC-1',
            label: 'E00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'WE',
            start_timestamp: 41400,
            start_time: '11:30',
            start_time_12hr: '11:30 am',
            end_timestamp: 46200,
            end_time: '12:50',
            end_time_12hr: '12:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Mohamad Hoda',
            session_type: 'FULLSESS',
            description: '',
          },
        },
      },
      F: {
        course_id: '1562',
        id: 'F',
        label: 'Section F',
        instructor: 'Wassim El Ahmar',
        description: 'This is a discription',
        num_components: 5,
        components: {
          'F01-LAB': {
            course_id: '1562',
            section_id: 'F',
            id: 'F01-LAB',
            guid: '2021winter1562FF01-LAB',
            label: 'F01-LAB',
            status: 'CLOSED',
            type: 'LAB',
            day: 'TH',
            start_timestamp: 41400,
            start_time: '11:30',
            start_time_12hr: '11:30 am',
            end_timestamp: 51600,
            end_time: '14:20',
            end_time_12hr: '2:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Wassim El Ahmar',
            session_type: 'FULLSESS',
            description: '',
          },
          'F02-LAB': {
            course_id: '1562',
            section_id: 'F',
            id: 'F02-LAB',
            guid: '2021winter1562FF02-LAB',
            label: 'F02-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'FR',
            start_timestamp: 30600,
            start_time: '08:30',
            start_time_12hr: '8:30 am',
            end_timestamp: 40800,
            end_time: '11:20',
            end_time_12hr: '11:20 am',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Wassim El Ahmar',
            session_type: 'FULLSESS',
            description: '',
          },
          'F03-LAB': {
            course_id: '1562',
            section_id: 'F',
            id: 'F03-LAB',
            guid: '2021winter1562FF03-LAB',
            label: 'F03-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 41400,
            start_time: '11:30',
            start_time_12hr: '11:30 am',
            end_timestamp: 51600,
            end_time: '14:20',
            end_time_12hr: '2:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Wassim El Ahmar',
            session_type: 'FULLSESS',
            description: '',
          },
          'F00-LEC-0': {
            course_id: '1562',
            section_id: 'F',
            id: 'F00-LEC-0',
            guid: '2021winter1562FF00-LEC-0',
            label: 'F00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'FR',
            start_timestamp: 41400,
            start_time: '11:30',
            start_time_12hr: '11:30 am',
            end_timestamp: 46200,
            end_time: '12:50',
            end_time_12hr: '12:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Wassim El Ahmar',
            session_type: 'FULLSESS',
            description: '',
          },
          'F00-LEC-1': {
            course_id: '1562',
            section_id: 'F',
            id: 'F00-LEC-1',
            guid: '2021winter1562FF00-LEC-1',
            label: 'F00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'WE',
            start_timestamp: 46800,
            start_time: '13:00',
            start_time_12hr: '1:00 pm',
            end_timestamp: 51600,
            end_time: '14:20',
            end_time_12hr: '2:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Wassim El Ahmar',
            session_type: 'FULLSESS',
            description: '',
          },
        },
      },
    },
  },
} as const;

export const iti_1121_winter_raw = {
  data: {
    id: 1563,
    school: 'uottawa',
    year: 2021,
    term: 'winter',
    subject_code: 'ITI',
    course_code: '1121',
    course_name: 'Introduction to Computing II',
    sections: {},
  },
} as const;

const csi_3131_winter_raw = {
  data: {
    id: 2931,
    school: 'uottawa',
    year: 2021,
    term: 'winter',
    subject_code: 'CSI',
    course_code: '3131',
    course_name: 'Operating Systems',
    sections: {
      A: {
        course_id: '2931',
        id: 'A',
        label: 'A',
        instructor: 'Fadi Malek',
        description: '',
        num_components: 7,
        components: {
          'A01-LAB': {
            course_id: '2931',
            section_id: 'A',
            id: 'A01-LAB',
            guid: '2021winter2931AA01-LAB',
            label: 'A01-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 57600,
            start_time: '16:00',
            start_time_12hr: '4:00 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
          'A02-LAB': {
            course_id: '2931',
            section_id: 'A',
            id: 'A02-LAB',
            guid: '2021winter2931AA02-LAB',
            label: 'A02-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 57600,
            start_time: '16:00',
            start_time_12hr: '4:00 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
          'A03-LAB': {
            course_id: '2931',
            section_id: 'A',
            id: 'A03-LAB',
            guid: '2021winter2931AA03-LAB',
            label: 'A03-LAB',
            status: 'OPEN',
            type: 'LAB',
            day: 'TU',
            start_timestamp: 57600,
            start_time: '16:00',
            start_time_12hr: '4:00 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
          'A00-LEC-0': {
            course_id: '2931',
            section_id: 'A',
            id: 'A00-LEC-0',
            guid: '2021winter2931AA00-LEC-0',
            label: 'A00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'TH',
            start_timestamp: 57600,
            start_time: '16:00',
            start_time_12hr: '4:00 pm',
            end_timestamp: 62400,
            end_time: '17:20',
            end_time_12hr: '5:20 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
          'A00-LEC-1': {
            course_id: '2931',
            section_id: 'A',
            id: 'A00-LEC-1',
            guid: '2021winter2931AA00-LEC-1',
            label: 'A00-LEC',
            status: 'OPEN',
            type: 'LEC',
            day: 'TU',
            start_timestamp: 63000,
            start_time: '17:30',
            start_time_12hr: '5:30 pm',
            end_timestamp: 67800,
            end_time: '18:50',
            end_time_12hr: '6:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
          'A04-TUT': {
            course_id: '2931',
            section_id: 'A',
            id: 'A04-TUT',
            guid: '2021winter2931AA04-TUT',
            label: 'A04-TUT',
            status: 'OPEN',
            type: 'TUT',
            day: 'TH',
            start_timestamp: 52200,
            start_time: '14:30',
            start_time_12hr: '2:30 pm',
            end_timestamp: 57000,
            end_time: '15:50',
            end_time_12hr: '3:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
          'A05-TUT': {
            course_id: '2931',
            section_id: 'A',
            id: 'A05-TUT',
            guid: '2021winter2931AA05-TUT',
            label: 'A05-TUT',
            status: 'OPEN',
            type: 'TUT',
            day: 'TH',
            start_timestamp: 52200,
            start_time: '14:30',
            start_time_12hr: '2:30 pm',
            end_timestamp: 57000,
            end_time: '15:50',
            end_time_12hr: '3:50 pm',
            start_date: '2021-01-11',
            end_date: '2021-04-14',
            room: '',
            instructor: 'Fadi Malek',
            session_type: 'FULLSESS',
            description: '',
          },
        },
      },
    },
  },
} as const;

const { data: csi2120_winter_data } = courseResponseSchema.parse(csi2120_winter_raw);
const { data: iti_1120_winter_data } = courseResponseSchema.parse(iti_1120_winter_raw);
const { data: iti_1121_winter_data } = courseResponseSchema.parse(iti_1121_winter_raw);
const { data: csi_3131_winter_data } = courseResponseSchema.parse(csi_3131_winter_raw);

// Export Course Testing Data
export const WINTER = {
  CSI_2120: new Course(csi2120_winter_data),
  ITI_1120: new Course(iti_1120_winter_data),
  ITI_1121: new Course(iti_1121_winter_data),
  CSI_3131: new Course(csi_3131_winter_data),
};

const secton_E_raw = iti_1120_winter_raw.data.sections.E;
const secton_F_raw = iti_1120_winter_raw.data.sections.F;

// Export CourseSection Testing Data
export const COURSE = WINTER.ITI_1120;

export const SECTIONS = {
  E: new CourseSection(WINTER.ITI_1120, secton_E_raw),
  F: new CourseSection(WINTER.ITI_1120, secton_F_raw),
};

// Export CourseSectionComponent Testing Data
const E00_LEC_0_raw = iti_1120_winter_raw.data.sections.E.components['E00-LEC-0'];
const E01_LAB_raw = iti_1120_winter_raw.data.sections.E.components['E01-LAB'];
const E05_LAB_raw = iti_1120_winter_raw.data.sections.E.components['E05-LAB'];

export const SECTION = WINTER.ITI_1120.sections.get('E') as CourseSection;

const A = WINTER.CSI_2120.sections.get('A') as CourseSection;

export const COMPONENTS = {
  E00_LEC_0: new CourseSectionComponent(SECTION, E00_LEC_0_raw),
  E01_LAB: new CourseSectionComponent(SECTION, E01_LAB_raw),
  E05_LAB: new CourseSectionComponent(SECTION, E05_LAB_raw),
  A00_LEC_0: A.components.get('A00-LEC-0') as CourseSectionComponent,
};
