"""
Django settings for uschedule project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import json
import notifier.logda
import boto3

ssm = boto3.client('ssm')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$_k&8z%b@3rk1zl1i9+nshnffz3u4!x4@6w+(=dju1abdy-z5o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ.get('DA_DEBUG') == 'true' else False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'www.uschedule.me', 'data-access']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django_filters',
    'rest_framework',
    'dry_rest_permissions',
    'data_access',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'data_access.auth.middleware.UScheduleJWTMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uschedule.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uschedule.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

creds = {}
if os.environ.get('USE_ENV_DB_CREDS', 'false').strip().lower() == 'true':
    creds = {
        "username": os.environ.get('DATABASE_USER'),
        "password": os.environ.get('DATABASE_PASS'),
    }
else:
    res = ssm.get_parameter(
        Name='/{}/data-access/db_credentials'.format(os.environ.get('ENV')),
        WithDecryption=True,
    )
    creds = json.loads(res['Parameter']['Value'])

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': creds['username'],
        'PASSWORD': creds['password'],
        'HOST': os.environ.get('DATABASE_HOST'),
    }
}
# Since this is a settings file avoid lingering vars just to be safe
del creds


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ([
        'uschedule.renderers.uScheduleRenderer',
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer',] if os.environ.get('DA_DEBUG') == 'true' else [])),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'data_access.auth.authenticators.UScheduleJWTAuthenticator',
    ],
}

# Logging
# https://docs.djangoproject.com/en/3.0/topics/logging/

#@TODO Fix propagation issues (django still propagates despite flag)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(asctime)s :: %(levelname)8s :: [%(name)s:%(filename)s:%(funcName)s] %(message)s',
            'style': '%',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'file': {
            '()': 'notifier.logda.ExceptionTracebackFormatter',
            'format': json.dumps({
                "time": "%(asctime)s", 
                "logger": "%(name)s",
                "level": "%(levelname)s", 
                "module": "%(module)s", 
                "pathname": "%(pathname)s", 
                "function": "%(funcName)s", 
                "lineno": "%(lineno)s", 
                "processno": "%(process)d", 
                "threadno": "%(thread)d", 
                "message": "%(message)s", 
                "exception": "%(exception)s", 
                "traceback": "%(traceback)s", 
            }),
            'style': '%',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
    },
    'handlers' : {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'level': 'DEBUG' if os.getenv("DA_DEBUG", "") == "true" else "INFO",
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': '/var/log/uschedule/da.log',
            'when': 'midnight',
            'utc': True,
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'uschedule.da': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'propagate': True,
        },
    },
}
