import { CourseData } from '@services/DataAccess';

export const test_data: Record<string, CourseData> = {};

test_data.csi2120 = {
  id: 3,
  sections: {
    A: {
      id: 'A',
      label: 'A',
      components: {
        'A01-LAB': {
          id: 'A01-LAB',
          day: 'MO',
          room: '800 King Edward (STE) 2060',
          type: 'LAB',
          label: 'A01-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '09:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '08:30',
          description: '',
          session_type: 'FullSess',
        },
        'A02-LAB': {
          id: 'A02-LAB',
          day: 'MO',
          room: '800 King Edward (STE) 2052',
          type: 'LAB',
          label: 'A02-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '09:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '08:30',
          description: '',
          session_type: 'FullSess',
        },
        'A03-LAB': {
          id: 'A03-LAB',
          day: 'MO',
          room: '800 King Edward (STE) 0131',
          type: 'LAB',
          label: 'A03-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '09:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '08:30',
          description: '',
          session_type: 'FullSess',
        },
        'A04-LAB': {
          id: 'A04-LAB',
          day: 'TH',
          room: '161 Louis Pasteur (CBY) B02',
          type: 'LAB',
          label: 'A04-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '11:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '10:00',
          description: '',
          session_type: 'FullSess',
        },
        'A05-LAB': {
          id: 'A05-LAB',
          day: 'TH',
          room: '800 King Edward (STE) 2060',
          type: 'LAB',
          label: 'A05-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '11:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '10:00',
          description: '',
          session_type: 'FullSess',
        },
        'A06-TUT': {
          id: 'A06-TUT',
          day: 'TH',
          room: '100 Louis Pasteur (CRX) C240',
          type: 'TUT',
          label: 'A06-TUT',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '17:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '16:00',
          description: '',
          session_type: 'FullSess',
        },
        'A07-LAB': {
          id: 'A07-LAB',
          day: 'TH',
          room: '161 Louis Pasteur (CBY) B02',
          type: 'LAB',
          label: 'A07-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '12:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '11:30',
          description: '',
          session_type: 'FullSess',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          day: 'TU',
          room: '100 Louis Pasteur (CRX) C140',
          type: 'LEC',
          label: 'A00-LEC',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '17:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '16:00',
          description: '',
          session_type: 'FullSess',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          day: 'TH',
          room: '100 Louis Pasteur (CRX) C140',
          type: 'LEC',
          label: 'A00-LEC',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '15:50',
          instructor: 'Staff',
          start_date: '2020-01-06',
          start_time: '14:30',
          description: '',
          session_type: 'FullSess',
        },
      },
      instructor: 'Jochen Lang',
      description: '',
    },
  },
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'CSI',
  course_code: '2120',
  course_name: 'Programming Paradigms',
};

test_data.csi3104 = {
  id: 9,
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'CSI',
  course_code: '3104',
  course_name: 'Introduction to Formal Languages',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      instructor: 'Amy Felty',
      description: '',
      components: {
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '550 Cumberland (TBT) 070',
          instructor: 'Amy Felty',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '550 Cumberland (TBT) 070',
          instructor: 'Amy Felty',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
  },
};

test_data.mat1348 = {
  id: 55,
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'MAT',
  course_code: '1348',
  course_name: 'Discrete Mathematics for Computing',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      instructor: 'Elizabeth Jane Maltais',
      description: '',
      components: {
        'A01-DGD': {
          id: 'A01-DGD',
          label: 'A01-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TU',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '55 Laurier (DMS) 1140',
          instructor: 'Elizabeth Jane Maltais',
          session_type: 'FullSess',
          description: '',
        },
        'A02-DGD': {
          id: 'A02-DGD',
          label: 'A02-DGD',
          status: 'CLOSED',
          type: 'DGD',
          day: 'TU',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '161 Louis Pasteur (CBY) B205',
          instructor: 'Elizabeth Jane Maltais',
          session_type: 'FullSess',
          description: '',
        },
        'A03-DGD': {
          id: 'A03-DGD',
          label: 'A03-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TU',
          start_time: '19:00',
          end_time: '20:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '161 Louis Pasteur (CBY) B205',
          instructor: 'Elizabeth Jane Maltais',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '125 University (MNT) 202',
          instructor: 'Elizabeth Jane Maltais',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '125 University (MNT) 202',
          instructor: 'Elizabeth Jane Maltais',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
    B: {
      id: 'B',
      label: 'B',
      instructor: 'Mathieu Lemire',
      description: '',
      components: {
        'B01-DGD': {
          id: 'B01-DGD',
          label: 'B01-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'FR',
          start_time: '08:30',
          end_time: '09:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '65 University (MRT) 250',
          instructor: 'Mathieu Lemire',
          session_type: 'FullSess',
          description: '',
        },
        'B02-DGD': {
          id: 'B02-DGD',
          label: 'B02-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'FR',
          start_time: '10:00',
          end_time: '11:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '65 University (MRT) 250',
          instructor: 'Mathieu Lemire',
          session_type: 'FullSess',
          description: '',
        },
        'B03-DGD': {
          id: 'B03-DGD',
          label: 'B03-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'FR',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '161 Louis Pasteur (CBY) B012',
          instructor: 'Mathieu Lemire',
          session_type: 'FullSess',
          description: '',
        },
        'B00-LEC-0': {
          id: 'B00-LEC-0',
          label: 'B00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) H0104',
          instructor: 'Mathieu Lemire',
          session_type: 'FullSess',
          description: '',
        },
        'B00-LEC-1': {
          id: 'B00-LEC-1',
          label: 'B00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) H0104',
          instructor: 'Mathieu Lemire',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
    C: {
      id: 'C',
      label: 'C',
      instructor: 'Hai Yan Liu',
      description: '',
      components: {
        'C01-DGD': {
          id: 'C01-DGD',
          label: 'C01-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TU',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) H0104',
          instructor: 'Hai Yan Liu',
          session_type: 'FullSess',
          description: '',
        },
        'C00-LEC-0': {
          id: 'C00-LEC-0',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '70 Laurier (MHN) 033',
          instructor: 'Hai Yan Liu',
          session_type: 'FullSess',
          description: '',
        },
        'C00-LEC-1': {
          id: 'C00-LEC-1',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '70 Laurier (MHN) 033',
          instructor: 'Hai Yan Liu',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
  },
};

test_data.csi3131 = {
  id: 10,
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'CSI',
  course_code: '3131',
  course_name: 'Operating Systems',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      instructor: 'Burak Kantarci',
      description: '',
      components: {
        'A01-LAB': {
          id: 'A01-LAB',
          label: 'A01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '161 Louis Pasteur (CBY) B02',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A02-LAB': {
          id: 'A02-LAB',
          label: 'A02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2060',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A03-LAB': {
          id: 'A03-LAB',
          label: 'A03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2052',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A04-TUT': {
          id: 'A04-TUT',
          label: 'A04-TUT',
          status: 'OPEN',
          type: 'TUT',
          day: 'TH',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '120 University (FSS) 2005',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A05-TUT': {
          id: 'A05-TUT',
          label: 'A05-TUT',
          status: 'OPEN',
          type: 'TUT',
          day: 'TH',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '129 Louis Pasteur (LPR) 155',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A06-LAB': {
          id: 'A06-LAB',
          label: 'A06-LAB',
          status: 'CLOSED',
          type: 'LAB',
          day: 'TU',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TU',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) H0104',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) H0104',
          instructor: 'Burak Kantarci',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
  },
};

test_data.iti1121 = {
  id: 186,
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'ITI',
  course_code: '1121',
  course_name: 'Introduction to Computing II',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      instructor: 'Guy-Vincent Jourdan',
      description: '',
      components: {
        'A01-LAB': {
          id: 'A01-LAB',
          label: 'A01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'MO',
          start_time: '19:00',
          end_time: '21:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0130',
          instructor: 'Guy-Vincent Jourdan',
          session_type: 'FULLSESS',
          description: '',
        },
        'A02-LAB': {
          id: 'A02-LAB',
          label: 'A02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '161 Louis Pasteur (CBY) B02',
          instructor: 'Guy-Vincent Jourdan',
          session_type: 'FULLSESS',
          description: '',
        },
        'A03-LAB': {
          id: 'A03-LAB',
          label: 'A03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '08:30',
          end_time: '11:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0131',
          instructor: 'Guy-Vincent Jourdan',
          session_type: 'FULLSESS',
          description: '',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) G0103',
          instructor: 'Guy-Vincent Jourdan',
          session_type: 'FULLSESS',
          description: '',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) G0103',
          instructor: 'Guy-Vincent Jourdan',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
    B: {
      id: 'B',
      label: 'B',
      instructor: 'Marcel Turcotte',
      description: '',
      components: {
        'B01-LAB': {
          id: 'B01-LAB',
          label: 'B01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'MO',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2060',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'B02-LAB': {
          id: 'B02-LAB',
          label: 'B02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '19:00',
          end_time: '21:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2060',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'B03-LAB': {
          id: 'B03-LAB',
          label: 'B03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0131',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'B00-LEC-0': {
          id: 'B00-LEC-0',
          label: 'B00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) G0103',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'B00-LEC-1': {
          id: 'B00-LEC-1',
          label: 'B00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'FR',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) G0103',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
    C: {
      id: 'C',
      label: 'C',
      instructor: 'Marcel Turcotte',
      description: '',
      components: {
        'C01-LAB': {
          id: 'C01-LAB',
          label: 'C01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2060',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'C02-LAB': {
          id: 'C02-LAB',
          label: 'C02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '19:00',
          end_time: '21:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0130',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'C03-LAB': {
          id: 'C03-LAB',
          label: 'C03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0131',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'C04-LAB': {
          id: 'C04-LAB',
          label: 'C04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '19:00',
          end_time: '21:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0130',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'C00-LEC-0': {
          id: 'C00-LEC-0',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '550 Cumberland (TBT) 333',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
        'C00-LEC-1': {
          id: 'C00-LEC-1',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '550 Cumberland (TBT) 333',
          instructor: 'Marcel Turcotte',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
    D: {
      id: 'D',
      label: 'D',
      instructor: 'Mehrdad Sabetzadeh',
      description: '',
      components: {
        'D01-LAB': {
          id: 'D01-LAB',
          label: 'D01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'FR',
          start_time: '11:30',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2060',
          instructor: 'Mehrdad Sabetzadeh',
          session_type: 'FULLSESS',
          description: '',
        },
        'D02-LAB': {
          id: 'D02-LAB',
          label: 'D02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 2052',
          instructor: 'Mehrdad Sabetzadeh',
          session_type: 'FULLSESS',
          description: '',
        },
        'D03-LAB': {
          id: 'D03-LAB',
          label: 'D03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'FR',
          start_time: '11:30',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) 0130',
          instructor: 'Mehrdad Sabetzadeh',
          session_type: 'FULLSESS',
          description: '',
        },
        'D00-LEC-0': {
          id: 'D00-LEC-0',
          label: 'D00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) G0103',
          instructor: 'Mehrdad Sabetzadeh',
          session_type: 'FULLSESS',
          description: '',
        },
        'D00-LEC-1': {
          id: 'D00-LEC-1',
          label: 'D00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) G0103',
          instructor: 'Mehrdad Sabetzadeh',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
  },
};

test_data.chm1321 = {
  id: 143,
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'CHM',
  course_code: '1321',
  course_name: 'Organic Chemistry I',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      instructor: 'William Walter Ogilvie',
      description: '',
      components: {
        'A01-DGD': {
          id: 'A01-DGD',
          label: 'A01-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TH',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '65 University (MRT) 218',
          instructor: 'William Walter Ogilvie',
          session_type: 'FullSess',
          description: '',
        },
        'A02-DGD': {
          id: 'A02-DGD',
          label: 'A02-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'MO',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '65 University (MRT) 205',
          instructor: 'William Walter Ogilvie',
          session_type: 'FullSess',
          description: '',
        },
        'A03-DGD': {
          id: 'A03-DGD',
          label: 'A03-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'WE',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '800 King Edward (STE) H0104',
          instructor: 'William Walter Ogilvie',
          session_type: 'FullSess',
          description: '',
        },
        'A04-DGD': {
          id: 'A04-DGD',
          label: 'A04-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TH',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '550 Cumberland (TBT) 333',
          instructor: 'William Walter Ogilvie',
          session_type: 'FullSess',
          description: '',
        },
        'Z01-LAB': {
          id: 'Z01-LAB',
          label: 'Z01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '11:00',
          start_date: '2020-03-24',
          end_date: '2020-03-24',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z02-LAB': {
          id: 'Z02-LAB',
          label: 'Z02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-31',
          end_date: '2020-03-31',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z03-LAB': {
          id: 'Z03-LAB',
          label: 'Z03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-24',
          end_date: '2020-03-24',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z04-LAB': {
          id: 'Z04-LAB',
          label: 'Z04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-31',
          end_date: '2020-03-31',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z05-LAB': {
          id: 'Z05-LAB',
          label: 'Z05-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-25',
          end_date: '2020-03-25',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z06-LAB': {
          id: 'Z06-LAB',
          label: 'Z06-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-04-01',
          end_date: '2020-04-01',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z07-LAB': {
          id: 'Z07-LAB',
          label: 'Z07-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-26',
          end_date: '2020-03-26',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z08-LAB': {
          id: 'Z08-LAB',
          label: 'Z08-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-04-02',
          end_date: '2020-04-02',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z09-LAB': {
          id: 'Z09-LAB',
          label: 'Z09-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-26',
          end_date: '2020-03-26',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z10-LAB': {
          id: 'Z10-LAB',
          label: 'Z10-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-04-02',
          end_date: '2020-04-02',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'William Walter Ogilvie',
          session_type: 'FullSess',
          description: '',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'FR',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'William Walter Ogilvie',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
    B: {
      id: 'B',
      label: 'B',
      instructor: 'Stephen Newman',
      description: '',
      components: {
        'B01-DGD': {
          id: 'B01-DGD',
          label: 'B01-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'WE',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '591 Cumberland (SCR) 002',
          instructor: 'Stephen Newman',
          session_type: 'FullSess',
          description: '',
        },
        'B02-DGD': {
          id: 'B02-DGD',
          label: 'B02-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'MO',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '100 Louis Pasteur (CRX) C140',
          instructor: 'Stephen Newman',
          session_type: 'FullSess',
          description: '',
        },
        'B03-DGD': {
          id: 'B03-DGD',
          label: 'B03-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'MO',
          start_time: '17:30',
          end_time: '18:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '150 Louis Pasteur (STM) 224',
          instructor: 'Stephen Newman',
          session_type: 'FullSess',
          description: '',
        },
        'Z01-LAB': {
          id: 'Z01-LAB',
          label: 'Z01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '11:00',
          start_date: '2020-03-24',
          end_date: '2020-03-24',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z02-LAB': {
          id: 'Z02-LAB',
          label: 'Z02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-31',
          end_date: '2020-03-31',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z03-LAB': {
          id: 'Z03-LAB',
          label: 'Z03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-24',
          end_date: '2020-03-24',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z04-LAB': {
          id: 'Z04-LAB',
          label: 'Z04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-31',
          end_date: '2020-03-31',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z05-LAB': {
          id: 'Z05-LAB',
          label: 'Z05-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-25',
          end_date: '2020-03-25',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z06-LAB': {
          id: 'Z06-LAB',
          label: 'Z06-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-04-01',
          end_date: '2020-04-01',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z07-LAB': {
          id: 'Z07-LAB',
          label: 'Z07-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-26',
          end_date: '2020-03-26',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z08-LAB': {
          id: 'Z08-LAB',
          label: 'Z08-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-04-02',
          end_date: '2020-04-02',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z09-LAB': {
          id: 'Z09-LAB',
          label: 'Z09-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-26',
          end_date: '2020-03-26',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z10-LAB': {
          id: 'Z10-LAB',
          label: 'Z10-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-04-02',
          end_date: '2020-04-02',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'B00-LEC-0': {
          id: 'B00-LEC-0',
          label: 'B00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'Stephen Newman',
          session_type: 'FullSess',
          description: '',
        },
        'B00-LEC-1': {
          id: 'B00-LEC-1',
          label: 'B00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TH',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'Stephen Newman',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
    C: {
      id: 'C',
      label: 'C',
      instructor: 'Kathy-Sarah Focsanéanu',
      description: '',
      components: {
        'C01-DGD': {
          id: 'C01-DGD',
          label: 'C01-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'WE',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '65 University (MRT) 218',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'C02-DGD': {
          id: 'C02-DGD',
          label: 'C02-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TH',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '591 Cumberland (SCR) 002',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'C03-DGD': {
          id: 'C03-DGD',
          label: 'C03-DGD',
          status: 'OPEN',
          type: 'DGD',
          day: 'TU',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z01-LAB': {
          id: 'Z01-LAB',
          label: 'Z01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '11:00',
          start_date: '2020-03-24',
          end_date: '2020-03-24',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z02-LAB': {
          id: 'Z02-LAB',
          label: 'Z02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-31',
          end_date: '2020-03-31',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z03-LAB': {
          id: 'Z03-LAB',
          label: 'Z03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-24',
          end_date: '2020-03-24',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z04-LAB': {
          id: 'Z04-LAB',
          label: 'Z04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-31',
          end_date: '2020-03-31',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z05-LAB': {
          id: 'Z05-LAB',
          label: 'Z05-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-25',
          end_date: '2020-03-25',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z06-LAB': {
          id: 'Z06-LAB',
          label: 'Z06-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-04-01',
          end_date: '2020-04-01',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z07-LAB': {
          id: 'Z07-LAB',
          label: 'Z07-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-03-26',
          end_date: '2020-03-26',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z08-LAB': {
          id: 'Z08-LAB',
          label: 'Z08-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2020-04-02',
          end_date: '2020-04-02',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z09-LAB': {
          id: 'Z09-LAB',
          label: 'Z09-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-03-26',
          end_date: '2020-03-26',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'Z10-LAB': {
          id: 'Z10-LAB',
          label: 'Z10-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2020-04-02',
          end_date: '2020-04-02',
          room: '140 Louis-Pasteur (MRN) 301',
          instructor: 'Unknown',
          session_type: 'FullSess',
          description: '',
        },
        'C00-LEC-0': {
          id: 'C00-LEC-0',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TU',
          start_time: '08:30',
          end_time: '09:50',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'Kathy-Sarah Focsanéanu',
          session_type: 'FullSess',
          description: '',
        },
        'C00-LEC-1': {
          id: 'C00-LEC-1',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'FR',
          start_time: '10:00',
          end_time: '11:20',
          start_date: '2020-01-06',
          end_date: '2020-04-04',
          room: '140 Louis-Pasteur (MRN) 150',
          instructor: 'Kathy-Sarah Focsanéanu',
          session_type: 'FullSess',
          description: '',
        },
      },
    },
  },
};
