# Generated by Django 3.0.8 on 2020-08-07 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('data_access', '0001_initial'), ('data_access', '0002_auto_20200208_1551'), ('data_access', '0003_auto_20200208_2144'), ('data_access', '0004_auto_20200218_0326')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', django.contrib.postgres.fields.jsonb.JSONField()),
                ('year', models.IntegerField()),
                ('term', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=5)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=255)),
                ('school', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=128)),
                ('provider_uid', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('disp_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='data_access.User')),
                ('notifications_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_comps', to='data_access.CourseData')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_comps', to='data_access.Schedule')),
                ('component_id', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
