# Generated by Django 3.0.3 on 2020-02-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0004_auto_20200218_0326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseData',
            new_name='Timetable',
        ),
    ]
