# Generated by Django 3.0.6 on 2020-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0005_auto_20200228_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date_created',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_updated',
            field=models.IntegerField(default=-1),
        ),
    ]
