# Generated by Django 3.0.6 on 2020-05-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0006_auto_20200518_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=72)),
                ('subject_code', models.CharField(max_length=5)),
                ('link', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
