# Generated by Django 3.0.7 on 2020-06-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0007_auto_20200522_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timestamp',
            unique_together={('reason',)},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'year', 'term', 'subject_code', 'course_code')},
        ),
    ]
