# Generated by Django 3.0.7 on 2020-06-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0008_auto_20200629_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
