# Generated by Django 3.1.1 on 2020-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0009_auto_20200629_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecomponents',
            name='component_id',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sections',
            field=models.JSONField(),
        ),
    ]
