# Generated by Django 3.1.2 on 2020-10-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0010_auto_20200921_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(choices=[('fall', 'Fall'), ('winter', 'Winter'), ('summer', 'Summer')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='term',
            field=models.CharField(choices=[('fall', 'Fall'), ('winter', 'Winter'), ('summer', 'Summer')], max_length=6),
        ),
    ]
