# Generated by Django 3.1.1 on 2020-12-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0011_auto_20201008_2209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availableterms',
            unique_together={('year', 'term')},
        ),
    ]
