# Generated by Django 3.1.6 on 2021-02-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0013_auto_20210214_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disp_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
