# Generated by Django 3.1.7 on 2021-03-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0014_auto_20210217_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='data_access.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='notifications_enabled',
        ),
        migrations.CreateModel(
            name='CalendarComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10)),
                ('component_id', models.CharField(max_length=10)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='data_access.calendar')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_components', to='data_access.timetable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='Calendar',
            constraint=models.UniqueConstraint(condition=models.Q(is_primary=True), fields=('user', 'is_primary'), name='single_primary_calendar_per_user'),
        ),
        migrations.DeleteModel(
            name='Schedule'
        ),
        migrations.DeleteModel(
            name='ScheduleComponents',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('fall', 'Fall'), ('winter', 'Winter'), ('summer', 'Summer')], max_length=6)),
                ('name', models.CharField(max_length=128, null=True)),
                ('year', models.IntegerField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='data_access.calendar')),
            ],
        ),
    ]
