# Generated by Django 3.1.7 on 2021-03-25 23:39

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    UserModel = apps.get_model('data_access', 'User')
    for row in UserModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0015_auto_20210307_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(null=False, unique=True)
        )
    ]
