# Generated by Django 3.1.7 on 2021-03-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0016_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='data_access.calendar')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares', to='data_access.user')),
            ],
        ),
    ]
