# Generated by Django 3.1.7 on 2021-03-28 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0017_calendarshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='term',
            field=models.CharField(choices=[('fall', 'Fall'), ('winter', 'Winter'), ('summer', 'Summer')], editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('calendar', 'term')},
        ),
    ]
