# Generated by Django 3.1.7 on 2021-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0018_auto_20210328_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
