# Generated by Django 3.1.7 on 2021-04-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0019_auto_20210402_1846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarshare',
            unique_together={('user', 'calendar')},
        ),
    ]
