# Generated by Django 3.2.4 on 2021-06-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0021_auto_20210426_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=5)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.IntegerField(default=-1)),
                ('date_updated', models.IntegerField(default=-1)),
            ],
            options={
                'unique_together': {('school', 'subject_code', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='ActivityAccreditationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='au_assignments', to='data_access.activity')),
                ('aus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to='data_access.accreditationunit')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='data_access.course'),
        ),
    ]
