# Generated by Django 3.2.4 on 2021-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0022_auto_20210618_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required_aus', models.JSONField()),
            ],
        ),
    ]
