# Generated by Django 3.2.4 on 2021-07-06 01:20

import data_access.models
from django.db import migrations

def gen_uuid(apps, schema_editor):
    for model_name in ('course', 'subject', 'timetable'):
        Model = apps.get_model('data_access', model_name)
        Model.objects.filter(subject_code__regex=r'[a-z]').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0023_accreditation'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='subject_code',
            field=data_access.models.UppercaseCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=data_access.models.UppercaseCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_code',
            field=data_access.models.UppercaseCharField(max_length=5),
        ),
    ]
