import { CourseData } from '@services/DataAccess';

export const ITI_1120_DATA: CourseData = {
  id: 2949,
  school: 'uottawa',
  year: 2021,
  season: 'fall',
  term: 'fall',
  subject_code: 'ITI',
  course_code: '1120',
  course_name: 'Introduction to Computing I',
  sections: {
    A: {
      id: 'A',
      label: 'A',
      instructor: 'Vida Dujmovic',
      description: '',
      components: {
        'A01-LAB': {
          id: 'A01-LAB',
          label: 'A01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '16:00',
          end_time: '18:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'A02-LAB': {
          id: 'A02-LAB',
          label: 'A02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '08:30',
          end_time: '11:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'A03-LAB': {
          id: 'A03-LAB',
          label: 'A03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '16:00',
          end_time: '18:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'A04-LAB': {
          id: 'A04-LAB',
          label: 'A04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'FR',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '13:00',
          end_time: '14:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          label: 'A00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '11:30',
          end_time: '12:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
    B: {
      id: 'B',
      label: 'B',
      instructor: 'Vida Dujmovic',
      description: '',
      components: {
        'B01-LAB': {
          id: 'B01-LAB',
          label: 'B01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TU',
          start_time: '10:00',
          end_time: '12:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'B02-LAB': {
          id: 'B02-LAB',
          label: 'B02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '19:00',
          end_time: '21:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'B03-LAB': {
          id: 'B03-LAB',
          label: 'B03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'TH',
          start_time: '16:00',
          end_time: '18:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'B04-LAB': {
          id: 'B04-LAB',
          label: 'B04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'FR',
          start_time: '17:30',
          end_time: '20:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'BB00-LEC-0': {
          id: 'BB00-LEC-0',
          label: 'BB00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'MO',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: '100 Louis Pasteur (CRX) C240',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'BB00-LEC-1': {
          id: 'BB00-LEC-1',
          label: 'BB00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '14:30',
          end_time: '16:00',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: '100 Louis Pasteur (CRX) C240',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
        'BV00-LEC-1': {
          id: 'BV00-LEC-1',
          label: 'BV00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'WE',
          start_time: '14:30',
          end_time: '16:00',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Vida Dujmovic',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
    C: {
      id: 'C',
      label: 'C',
      instructor: '',
      description: '',
      components: {
        'C01-LAB': {
          id: 'C01-LAB',
          label: 'C01-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'MO',
          start_time: '08:30',
          end_time: '11:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Unknown',
          session_type: 'FULLSESS',
          description: '',
        },
        'C02-LAB': {
          id: 'C02-LAB',
          label: 'C02-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'MO',
          start_time: '14:30',
          end_time: '17:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Unknown',
          session_type: 'FULLSESS',
          description: '',
        },
        'C03-LAB': {
          id: 'C03-LAB',
          label: 'C03-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'WE',
          start_time: '08:30',
          end_time: '11:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Unknown',
          session_type: 'FULLSESS',
          description: '',
        },
        'C04-LAB': {
          id: 'C04-LAB',
          label: 'C04-LAB',
          status: 'OPEN',
          type: 'LAB',
          day: 'FR',
          start_time: '08:30',
          end_time: '11:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Unknown',
          session_type: 'FULLSESS',
          description: '',
        },
        'C00-LEC-0': {
          id: 'C00-LEC-0',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'FR',
          start_time: '16:00',
          end_time: '17:20',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Unknown',
          session_type: 'FULLSESS',
          description: '',
        },
        'C00-LEC-1': {
          id: 'C00-LEC-1',
          label: 'C00-LEC',
          status: 'OPEN',
          type: 'LEC',
          day: 'TU',
          start_time: '14:30',
          end_time: '15:50',
          start_date: '2021-09-08',
          end_date: '2021-12-08',
          room: 'Virtual',
          instructor: 'Unknown',
          session_type: 'FULLSESS',
          description: '',
        },
      },
    },
  },
};

export const CSI_2120_DATA: CourseData = {
  id: 3,
  sections: {
    A: {
      id: 'A',
      label: 'A',
      components: {
        'A01-LAB': {
          id: 'A01-LAB',
          day: 'MO',
          room: '800 King Edward (STE) 2060',
          type: 'LAB',
          label: 'A01-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '09:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '08:30',
          description: '',
          session_type: 'FullSess',
        },
        'A02-LAB': {
          id: 'A02-LAB',
          day: 'MO',
          room: '800 King Edward (STE) 2052',
          type: 'LAB',
          label: 'A02-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '09:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '08:30',
          description: '',
          session_type: 'FullSess',
        },
        'A03-LAB': {
          id: 'A03-LAB',
          day: 'MO',
          room: '800 King Edward (STE) 0131',
          type: 'LAB',
          label: 'A03-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '09:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '08:30',
          description: '',
          session_type: 'FullSess',
        },
        'A04-LAB': {
          id: 'A04-LAB',
          day: 'TH',
          room: '161 Louis Pasteur (CBY) B02',
          type: 'LAB',
          label: 'A04-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '11:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '10:00',
          description: '',
          session_type: 'FullSess',
        },
        'A05-LAB': {
          id: 'A05-LAB',
          day: 'TH',
          room: '800 King Edward (STE) 2060',
          type: 'LAB',
          label: 'A05-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '11:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '10:00',
          description: '',
          session_type: 'FullSess',
        },
        'A06-TUT': {
          id: 'A06-TUT',
          day: 'TH',
          room: '100 Louis Pasteur (CRX) C240',
          type: 'TUT',
          label: 'A06-TUT',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '17:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '16:00',
          description: '',
          session_type: 'FullSess',
        },
        'A07-LAB': {
          id: 'A07-LAB',
          day: 'TH',
          room: '161 Louis Pasteur (CBY) B02',
          type: 'LAB',
          label: 'A07-LAB',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '12:50',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '11:30',
          description: '',
          session_type: 'FullSess',
        },
        'A00-LEC-0': {
          id: 'A00-LEC-0',
          day: 'TU',
          room: '100 Louis Pasteur (CRX) C140',
          type: 'LEC',
          label: 'A00-LEC',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '17:20',
          instructor: 'Jochen Lang',
          start_date: '2020-01-06',
          start_time: '16:00',
          description: '',
          session_type: 'FullSess',
        },
        'A00-LEC-1': {
          id: 'A00-LEC-1',
          day: 'TH',
          room: '100 Louis Pasteur (CRX) C140',
          type: 'LEC',
          label: 'A00-LEC',
          status: 'OPEN',
          end_date: '2020-04-04',
          end_time: '15:50',
          instructor: 'Staff',
          start_date: '2020-01-06',
          start_time: '14:30',
          description: '',
          session_type: 'FullSess',
        },
      },
      instructor: 'Jochen Lang',
      description: '',
    },
  },
  school: 'uottawa',
  year: 2020,
  term: 'winter',
  subject_code: 'CSI',
  course_code: '2120',
  course_name: 'Programming Paradigms',
};
